<a href="https://colab.research.google.com/github/kakkiichan/Machine-Learning/blob/master/Unsupervised/Iris_PCA_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_iris
ds = load_iris()

In [57]:
iris_data = ds.data
iris_target = ds.target
iris_feature= ds.feature_names

iris = pd.DataFrame(data=iris_data,columns=iris_feature)
iris_target =pd.DataFrame(data=iris_target,columns=["class"])

iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [0]:
iris_n = iris.iloc[:, :].apply(lambda x: (x-x.mean())/x.std(), axis=0)

In [59]:
iris_c = iris.corr()
iris_c

sepal length (cm)  ...  petal width (cm)
sepal length (cm)           1.000000  ...          0.817941
sepal width (cm)           -0.117570  ...         -0.366126
petal length (cm)           0.871754  ...          0.962865
petal width (cm)            0.817941  ...          1.000000

[4 rows x 4 columns]

In [60]:
# 固有値と固有ベクトル
eig_val, eig_vec =np.linalg.eig(iris_c)

# 固有値
eig_val

array([2.91849782, 0.91403047, 0.14675688, 0.02071484])

In [61]:
# 固有ベクトル
eig_vec

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

In [62]:
eig_vec_pc1 = eig_vec[:, 0]
eig_vec_pc1

array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])

In [63]:
# 主成分得点(PC1)
pc1 = np.dot(iris_n, eig_vec_pc1)
pc1

array([-2.25714118, -2.07401302, -2.35633511, -2.29170679, -2.3818627 ,
       -2.06870061, -2.43586845, -2.22539189, -2.32684533, -2.17703491,
       -2.15907699, -2.31836413, -2.2110437 , -2.62430902, -2.19139921,
       -2.25466121, -2.20021676, -2.18303613, -1.89223284, -2.33554476,
       -1.90793125, -2.19964383, -2.76508142, -1.81259716, -2.21972701,
       -1.9453293 , -2.04430277, -2.1613365 , -2.13241965, -2.25769799,
       -2.13297647, -1.82547925, -2.60621687, -2.43800983, -2.10292986,
       -2.20043723, -2.03831765, -2.51889339, -2.42152026, -2.16246625,
       -2.27884081, -1.85191836, -2.54511203, -1.95788857, -2.12992356,
       -2.06283361, -2.37677076, -2.38638171, -2.22200263, -2.19647504,
        1.09810244,  0.72889556,  1.2368358 ,  0.40612251,  1.07188379,
        0.38738955,  0.74403715, -0.48569562,  0.92480346,  0.01138804,
       -0.10982834,  0.43922201,  0.56023148,  0.71715934, -0.03324333,
        0.87248429,  0.34908221,  0.1582798 ,  1.22100316,  0.16

In [64]:
# 相関行列の固有値の第1成分を、主成分分析では「第1主成分(PC1)の固有値」と言います
eig_val_pc1 = eig_val[0]
eig_val_pc1

2.9184978165319957

In [68]:
# 相関行列から、PC1の影響を取り除いた相関行列2を作成します
matrix = []
for d1 in eig_vec_pc1:
    mat = []
    for d2 in eig_vec_pc1:
        mat.append(d1 * d2)
    matrix.append(mat)
matrix = np.array(matrix)
dfc2 = iris_c - matrix * eig_val_pc1
dfc2

sepal length (cm)  ...  petal width (cm)
sepal length (cm)           0.207600  ...         -0.041053
sepal width (cm)            0.292035  ...          0.077902
petal length (cm)          -0.010898  ...          0.006036
petal width (cm)           -0.041053  ...          0.068816

[4 rows x 4 columns]

In [69]:
# 固有値と固有ベクトル
eig_val2, eig_vec2 =np.linalg.eig(dfc2)

# 固有値
eig_val2

array([ 9.14030471e-01,  1.46756876e-01, -1.52995455e-15,  2.07148364e-02])

In [70]:
#固有ベクトル
eig_vec2

array([[ 0.37741762,  0.71956635,  0.52106591,  0.26128628],
       [ 0.92329566, -0.24438178, -0.26934744, -0.12350962],
       [ 0.02449161, -0.14212637,  0.5804131 , -0.80144925],
       [ 0.06694199, -0.63427274,  0.56485654,  0.52359713]])

In [71]:
eig_vec_pc2 = eig_vec2[:, 0]
eig_vec_pc2

array([0.37741762, 0.92329566, 0.02449161, 0.06694199])

In [72]:
# 相関行列2の固有値の第1成分を、主成分分析では「第2主成分(PC2)の固有値」と言います
eig_val_pc2 = eig_val2[0]
eig_val_pc2

0.9140304714680701

In [98]:
# 相関行列2から、PC2の影響を取り除いた相関行列3を作成します
matrix = []
for d1 in eig_vec_pc2:
    mat = []
    for d2 in eig_vec_pc2:
        mat.append(d1 * d2)
    matrix.append(mat)
matrix = np.array(matrix)
dfc3 = dfc2 - matrix * eig_vec_pc2
dfc3

sepal length (cm)  ...  petal width (cm)
sepal length (cm)           0.153839  ...         -0.042744
sepal width (cm)            0.160517  ...          0.073765
petal length (cm)          -0.014386  ...          0.005926
petal width (cm)           -0.050588  ...          0.068516

[4 rows x 4 columns]

In [99]:
# 固有値と固有ベクトル
eig_val3, eig_vec3 =np.linalg.eig(dfc3)

# 固有値
eig_val3

array([ 1.46756876e-01,  7.28685500e-02, -1.27322237e-15,  2.07148364e-02])

In [100]:
eig_vec3

array([[ 0.7165528 ,  0.37741762, -0.11590412,  0.13478603],
       [ 0.62638665,  0.92329566, -0.94920678,  0.80171065],
       [-0.05961036,  0.02449161,  0.22812552,  0.51518999],
       [-0.30106222,  0.06694199,  0.183116  , -0.27142592]])

In [101]:
eig_vec_pc3 = eig_vec3[:, 0]
eig_vec_pc3

array([ 0.7165528 ,  0.62638665, -0.05961036, -0.30106222])

In [102]:
# 相関行列3の固有値の第1成分を、主成分分析では「第3主成分(PC3)の固有値」と言います
eig_val_pc3 = eig_val3[0]
eig_val_pc3

0.14675687557131445

In [104]:
# 相関行列3から、PC3の影響を取り除いた相関行列4を作成します
matrix = []
for d1 in eig_vec_pc3:
    mat = []
    for d2 in eig_vec_pc3:
        mat.append(d1 * d2)
    matrix.append(mat)
matrix = np.array(matrix)
dfc4 = dfc3 - matrix * eig_vec_pc3
dfc4

sepal length (cm)  ...  petal width (cm)
sepal length (cm)          -0.214074  ...         -0.107692
sepal width (cm)           -0.161100  ...          0.016990
petal length (cm)           0.016220  ...          0.011329
petal width (cm)            0.103991  ...          0.095803

[4 rows x 4 columns]

In [105]:
# 固有値と固有ベクトル
eig_val4, eig_vec4 =np.linalg.eig(dfc4)

# 固有値
eig_val4

array([-4.39425236e-01,  7.28685500e-02, -1.22383845e-15,  2.07148364e-02])

In [106]:
eig_vec4

array([[ 0.7165528 ,  0.65581495,  0.80688711,  0.5535999 ],
       [ 0.62638665, -0.37828207, -0.51621225, -0.40193847],
       [-0.05961036, -0.14418574,  0.24764758, -0.72793518],
       [-0.30106222, -0.63719691, -0.14535744,  0.04563986]])

In [94]:
eig_vec_pc4 = eig_vec4[:, 0]
eig_vec_pc4

array([ 0.7165528 ,  0.62638665, -0.05961036, -0.30106222])

In [95]:
# 相関行列4の固有値の第1成分を、主成分分析では「第4主成分(PC4)の固有値」と言います
eig_val_pc4 = eig_val4[0]
eig_val_pc4

-0.4394252358736846

In [96]:
eig_val_pca = np.array([eig_val_pc1, eig_val_pc2, eig_val_pc3, eig_val_pc4])
eig_val_pca

array([ 2.91849782,  0.91403047,  0.14675688, -0.43942524])

In [97]:
eig_val_pca / eig_val_pca.sum()

array([ 0.82446703,  0.25821092,  0.04145838, -0.12413633])

◯参考
https://qiita.com/maskot1977/items/082557fcda78c4cdb41f