<a href="https://colab.research.google.com/github/kakkiichan/Machine-Learning/blob/master/Deep-Learning/Iris_Multiclass_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
X = iris.data
T = iris.target
T

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# One-vs-Rest な配列に変換
from keras.utils import np_utils
T = np_utils.to_categorical(T)

Using TensorFlow backend.


In [7]:
T

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [9]:
from sklearn.model_selection import train_test_split
import numpy as np
np.random.seed(0) # 乱数初期化を固定値に
train_x, test_x, train_t, test_t = train_test_split(X, T, train_size=0.8, test_size=0.2)
len(train_x), len(test_x), len(train_t), len(test_t) # サイズ表示


(120, 30, 120, 30)

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
          
model = Sequential()
model.add(Dense(input_dim=4, units=3)) # 入力が4種の特徴、3つに分離
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))
model.fit(train_x, train_t, epochs=50, batch_size=10) # エポック50, ミニバッチ 10






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/50





120/120 [==============================] - 1s 4ms/step - loss: 1.7483
Epoch 2/50
120/120 [==============================] - 0s 163us/step - loss: 0.8176
Epoch 3/50
120/120 [==============================] - 0s 140us/step - loss: 0.9922
Epoch 4/50
120/120 [==============================] - 0s 135us/step - loss: 0.7833
Epoch 5/50
120/120 [==============================] - 0s 128us/step - loss: 0.5650
Epoch 6/50
120/120 [==============================] - 0s 126us/step - loss: 0.4934
Epoch 7/50
120/120 [==============================] - 0s 132us/step - loss: 0.8877
Epoch 8/50
120/120 [==============================] - 0s 134us/step - loss: 0.7910
Epoch 9/50
120/120 [==============================] - 0s 141us/step - loss: 0.6218
Epoch 10/50
120/120 [==============================] - 0s 156us/step - loss: 0.4507
Epoch 11/50
120/120 [==============================] - 0s 139us/

In [12]:
Y = model.predict_classes(test_x, batch_size=10) # ミニバッチは訓練時と同じく 10
Y

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 1, 1, 0])

In [13]:
import numpy as np
_, T_index = np.where(test_t > 0)
print(T_index)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [14]:
Y == T_index

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])

参考

https://www.infiniteloop.co.jp/blog/2018/01/learning-keras-04/